### ISSUE TITLE
__hloop_process_timers 发生core，如何定位？

### ISSUE THREAD

**Issue by jackeyt** [ithewei/libhv#651]
coredump发生在__hloop_process_timers 
```
(gdb) bt
#0  0xb6e09b68 in __hloop_process_timers () from lib/libhv.so
#1  0xb6e0a1e0 in hloop_process_events () from lib/libhv.so
#2  0xb6e0b718 in hloop_run () from lib/libhv.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

- 问题1：__hloop_process_timers 这个接口中比较可能出现coredump的代码是哪里？
- 问题2：我当时发生core的时候并没有去使用-O0的库，在发生后编译了O0的库，用gdb的调试手段去替换旧的库，但是没有起效，有没有方式可以共享一下？

**Comment by ithewei** [comment]
是不是在其它线程调用了htimer_add、htimer_del等接口导致？这些接口不是线程安全的

**Comment by jackeyt** [comment]
在一个线程里面，并不是多线程的使用：
频繁的调用htimer_add添加一个repeat=1的定时器，会导致libhv内部的htimer_del崩溃
gdb 信息如下：
![Image](https://github.com/user-attachments/assets/2ffbd30a-5c55-4f76-b933-6e9c7e35347e)

**Comment by wujin1989** [comment]
> htimer_del

是不是htimer_add执行的任务里又调用了htimer_del

**Comment by ithewei** [comment]
你是在哪里调用的htimer_add，htimer_add需要在loop所在线程调用，hloop_run前或者hloop_run后loop线程所在的回调函数里
